import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="max-w-lg mx-auto border shadow-sm p-4 mt-4">{children}</body>
    </html>
  );
}
